[project]
name = "gemini-translate"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12.4"
dependencies = [
    "google-genai>=1.8.0",
    "google-generativeai>=0.8.4",
    "rich>=13.9.4",
]
